version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    container_name: task_manager_backend

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: task_manager_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/tasks
    depends_on:
      - backend